### ISSUE TITLE
FileNotFoundError during INFERENCE:

### ISSUE THREAD

**Issue by mudassarayub123456** [wanghao9610/TMANet#29]
File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/tifffile/tifffile.py", line 9550, in open
    self._fh = open(self._file, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: '/mydrive/Mudassar/data/test/s2_uc1_data_region_GO_raw_/camvid_format_uc1/images_sequence/0001TP_0000.tif'
I dont have 0001TP_0000.tif my images start with 0001TP_0001.tif' but it finds 0001TP_0000 which is not avialbel, first time it runs properly and after that it thhrows erroe complete noup error is attached below
2023-08-01 16:02:26,870 - mmseg - INFO - Loaded 95 images
show_dir: None False
[                                                  ] 0/95, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./tools/test.py", line 186, in <module>
    main()
  File "./tools/test.py", line 161, in main
    outputs = single_gpu_test(model, data_loader, args.show, args.show_dir)
  File "/mydrive/Mudassar/TMANet_multiband_infrence/./tools/../mmseg/apis/test.py", line 35, in single_gpu_test
    for i, data in enumerate(data_loader):
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mydrive/Mudassar/TMANet_multiband_infrence/./tools/../mmseg/datasets/custom_video.py", line 302, in __getitem__
    return self.prepare_test_img(idx)
  File "/mydrive/Mudassar/TMANet_multiband_infrence/./tools/../mmseg/datasets/custom_video.py", line 339, in prepare_test_img
    return self.pipeline(results)
  File "/mydrive/Mudassar/TMANet_multiband_infrence/./tools/../mmseg/datasets/pipelines/compose.py", line 43, in __call__
    data = t(data)
  File "/mydrive/Mudassar/TMANet_multiband_infrence/./tools/../mmseg/datasets/pipelines/loading.py", line 78, in __call__
    frame = tifffile.imread(frame_filename)
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/tifffile/tifffile.py", line 816, in imread
    with TiffFile(files, **kwargs_file) as tif:
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/tifffile/tifffile.py", line 3000, in __init__
    fh = FileHandle(arg, mode=mode, name=name, offset=offset, size=size)
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/tifffile/tifffile.py", line 9537, in __init__
    self.open()
  File "/home/haris/.conda/envs/mudassar_TMA/lib/python3.8/site-packages/tifffile/tifffile.py", line 9550, in open
    self._fh = open(self._file, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: '/mydrive/Mudassar/data/test/s2_uc1_data_region_GO_raw_/camvid_format_uc1/images_sequence/0001TP_0000.tif'

**Comment by wanghao9610** [comment]
Sorry to give response so late. This error indicattes your file error, which is not found. If you want to test camvid，first you should prepare the data follow README.md .
